- README.md
- crypto/README.md
- crypto/mimc7/mimc7.go
- crypto/mimc7/mimc7_test.go
- go.mod
- go.sum
> mimc7 hash implemented

- crypto/mimc7/mimc7.go
> Avoid using append

- core/claim.go
- core/claim_test.go
- merkletree/merkletree.go
- merkletree/node.go
> Sync claims to spec and update tests

- merkletree/merkletree.go
- merkletree/merkletree_test.go
Resolve #54
Also format test vectors in a pretty way :unicorn:
> Fix NewProofFromBytes for proof with aux node, add tests

- cmd/relay/endpoint/name.go
- cmd/relay/endpoint/serve.go
- utils/signatures_test.go
small update adding ProofOfClaimAssignName in nameresolver, and added utils/signature tests
> small update adding proof of claim in nameresolver, and added utils/signature tests

- core/proof.go
> proof data structs with lower cammelCase (aka dromedaryCase)

- merkletree/merkletree.go
- merkletree/merkletree_test.go
Iterate over nodes of all branches of a tree snapshot with specific root, allowing to dump claims, generate graphviz, etc
resolves #75, resolves #36
> Add mt.Walk tree iterator, used by mt.GraphViz and mt.DumpClaims

- Relay.md
- cmd/relay/commands/id.go
- cmd/relay/endpoint/claim.go
- cmd/relay/endpoint/id.go
- cmd/relay/endpoint/name.go
- cmd/relay/endpoint/serve.go
- core/claim.go
- core/proof.go
- services/backupsrv/messages.go
- services/backupsrv/service_test.go
- services/claimsrv/claimproofs.go
- services/claimsrv/messages.go
- services/claimsrv/service.go
- services/identitysrv/service.go
- services/namesrv/messages.go
- services/namesrv/service.go
- utils/utils.go
naming consensus for id endpoints and jsons working with iden3js
> Update naming consensus, works with iden3js

- README.md
- cmd/backupserver/README.md
- cmd/backupserver/config/load.go
- cmd/backupserver/endpoint/backup.go
- cmd/backupserver/endpoint/serve.go
- cmd/backupserver/endpoint/sync.go
- cmd/backupserver/main.go
- cmd/backupserver/test_backup.py
- services/backupsrv/messages.go
- services/backupsrv/service.go
> Add backupsrv Register, BackupUpload, BackupDownload, with api endpoints

- cmd/claimserver/.gitignore
- cmd/claimserver/commands/claim.go
- cmd/claimserver/commands/db.go
- cmd/claimserver/commands/server.go
- cmd/claimserver/config.example.yaml
- cmd/claimserver/config/config.go
- cmd/claimserver/config/load.go
- cmd/claimserver/endpoint/admin.go
- cmd/claimserver/endpoint/claim.go
- cmd/claimserver/endpoint/serve.go
- cmd/claimserver/endpoint/utils.go
- cmd/claimserver/main.go
- cmd/claimserver/test_endpoints.py
- cmd/relay/config.example.yaml
> claimserver

- cmd/claimserver/commands/claim.go
- cmd/relay/commands/claim.go
- core/proof.go
- merkletree/merkletree.go
- merkletree/merkletree_test.go
- merkletreeDoc/example.go
- merkletreeDoc/merkletree.md
- services/claimsrv/service.go
> allow mt.GenerateProof to specify tree Root

- core/claim.go
- core/claim_test.go
- Add claim implementation
- Add claim test
> add claim link-object-identity

- cmd/backupserver/endpoint/serve.go
- cmd/claimserver/endpoint/serve.go
- cmd/genericserver/server.go
- cmd/nameserver/endpoint/serve.go
- cmd/relay/endpoint/serve.go
- services/identitysrv/service_test.go
> Fail if listen doesn't succeed

- crypto/field/field.go
- crypto/field/field_test.go
- crypto/mimc7/mimc7.go
- crypto/mimc7/mimc7_test.go
To ensure compatibility among future changes
> put finite field over R operations in this repo instead of importing, update mimc7 using it

- services/identityagentsrv/service.go
- services/identityagentsrv/service_test.go
> agent.GetCurrentRoot returns local & published root

- keystore/keystore.go
- keystore/keystore_test.go
- services/claimsrv/messages.go
- services/claimsrv/service.go
- services/signedpacketsrv/service.go
- services/signsrv/service.go
> keystore: sign & verify with prefix and date

- services/claimsrv/service.go
- services/identityagentsrv/service.go
- services/identityagentsrv/service_test.go
> check SetRoot0Req on identity RootUpdate

- go.mod
- go.sum
> update go-ethereum version to v1.9.3

- components/idenmanager/idenmanager_test.go
- core/id.go
- core/id_test.go
> reset ID type for new spec

- .travis.yml
- go.mod
> Bump go version to 1.13

- core/claims/claimAssignName_test.go
- core/claims/claimAuthorizeEthKey_test.go
- core/claims/claimAuthorizeKSignBabyJub_test.go
- core/claims/claimAuthorizeKSignSecp256k1_test.go
- core/claims/claimAuthorizeService_test.go
- core/claims/claimBasic_test.go
- core/claims/claimEthId_test.go
- core/claims/claimLinkObjectIdentity_test.go
- core/claims/claimSetRootKey_test.go
- core/genesis/genesis_test.go
- core/id_test.go
- core/proof/proof_test.go
Initialize and finalize test in TestMain when possible.
Resolve #253
> Init and finalize test in TestMain

- common/common.go
- components/idenadminutils/idenadminutils.go
- components/idenmanager/claimproofs.go
- components/idenmanager/idenmanager_test.go
- core/claims/claimAuthorizeKSignBabyJub_test.go
- core/claims/claimLinkObjectIdentity.go
- core/genesis/genesis_test.go
- core/proof/proof.go
- core/proof/proof_test.go
- core/testVectors/id.json
- db/storage_test.go
- eth/client.go
- eth/client2.go
- eth/contract.go
- keystore/keystore.go
- keystore/keystore_test.go
- merkletree/merkletree.go
- merkletree/merkletree_test.go
- merkletree/node.go
- merkletree/utils.go
- testgen/testgen.go
- utils/utils.go
Fix all warnings thrown by the linter.
Closes #234
> Fix all linter warnings

- components/idenadminutils/idenadminutils.go
> Remove gin dependency in IdenAdminUtils.RawDump

- components/idenmanager/claimproofs.go
- components/identity/holder/holder.go
- components/identity/identity.go
- components/identity/issuer/issuer.go
- components/verifier/verifier.go
- core/proof/proof.go
> Add new identity structure

- core/genesis/genesis.go
- core/genesis/genesis_test.go
- core/genesis/testVectors/genesis.json
- core/id.go
- core/proof/proof.go
> Update genesis to use identity state

- components/identity/issuer/issuer.go
- components/identity/issuer/issuer_test.go
- components/identity/issuer/noncegen.go
- components/identity/issuer/noncegen_test.go
- components/identity/issuer/storageutils.go
- components/identity/issuer/storageutils_test.go
- merkletree/merkletree_test.go
> Add storage utils for issuer

- merkletree/merkletree_test.go
Update `BenchAddEntry` to:
First, populate the merkletree, and then perform benchmarks adding multiple times the same Entry in copies of the merkletree (instead of adding different Entry in a different tree (as it was growing) each time). This is done in order to have a more isolated benchmark of AddEntry.
Can be used to generate flamegraphs as the following:
> Update merkletree BenchAddEntry to isolate AddEntry

- components/idenpubonchain/idenpubonchain.go
- core/claims/claim.go
- crypto/ecdsa_public_key.go
- crypto/signatures.go
- identity/issuer/issuer.go
- merkletree/merkletree.go
- merkletree/utils.go
> Return error on empty identity

- components/verifier/verifier.go
- components/verifier/verifier_test.go
> Add expiration check in verify credential

- components/httpclient/httpclient.go
- components/httpclient/httpclient_test.go
> Fix http client validation, add test

- db/storageutils.go
- identity/issuer/issuer.go
Resolve https://github.com/iden3/iden3-mobile/issues/57
> Return error in db.LoadJSON when missing kv

- go.mod
- go.sum
- keystore/keystore.go
First step to address https://github.com/iden3/iden3-mobile/issues/59
> Remove logs from keystore.  Close returns error

- identity/issuer/issuer.go
Sorry about this, it slipped into a previous PR.
> Clean debug prints

- components/verifier/verifier_test.go
- go.mod
- go.sum
- utils/zk/zk.go
- utils/zk/zk_test.go
- Update deps
- add PubSignal type
- Fix claimDemo input construction
> Update deps, add PubSignal type

- utils/zk/zk.go
The added function utilities are meant to be used from a cli to easily download and calculate the hashes of the zkfiles to be added in a configuration file.  Once this is merged, a PR to servers will come with such cli.
> Add zkfiles utils to download and hash without checks

- components/idenpuboffchain/writerhttp/writerhttp.go
- components/verifier/verifier_test.go
- identity/holder/holder.go
- identity/issuer/issuer_test.go
- merkletree/merkletree.go
> Fix IdenPubOffChainWriteHttp with CacheLen > 1

- utils/zk/zk.go
This allows concurrent use of multiple ZkFiles instances using the same path.  When one instance is downloading the files, the other instances will be blocked and wait.
> Add file locking for concurrent use of ZkFiles

- utils/zk/zk.go
Resolve #392 
There were some public methods that were modifying and checking internal fields.  Now all public methods acquire a lock so that all methods can be called concurrently.
> Make all ZkFiles operations thread safe

- did.go
- did_test.go
Resolves a panic in the ParseDID function when correctly parsing a readonly id
> Resolve ParseDID panic when correctly parsing readonly id

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- did_test.go
- id.go
- id_test.go
> Put checksum little endian

- id.go
- id_test.go
Update ProfileID function, to have the same logic as we have in circuits.
> Update ProfileID, return user id if profile null or zero
