cmd/relay/endpoint/rest.go, core/claim.go, core/claim_test.go, services/claim/claim.go, services/claim/claim_test.go
New Claim data structure
```
|     32    |  24  |      4      |    4    |    x       |   y    |
| Namespace | Type | IndexLength | Version | ExtraIndex |  Data  |
| --------------------Index-----------------------------|--Data--|
Namespace: 32 bytes, Hash(namespace)
Type: 24 bytes, Hash(type)[:24]
IndexLength: 4 bytes, from uint32
Version: 4 bytes, from uint32
```
Updated data structure in all operations, updated tests
=> updated claim index data structure, added BaseIndex.IndexLength param eter, cropped Type parameter to Hash()[:24]

core/claim.go, core/claim_test.go, merkletree/merkletree.go, merkletree/merkletreeSpecification_test.go, merkletree/merkletree_test.go, merkletree/node.go, merkletree/print.go, merkletree/utils.go, merkletree/utils_test.go, services/backupsrv/service.go, services/backupsrv/service_test.go, services/namesrv/messages.go, services/namesrv/service.go, utils/hash.go, utils/hash_test.go, utils/signatures.go, utils/signatures_test.go, utils/utils.go, utils/utils_test.go
Solves issue #42 
I have added a placeholder HashBytes function in the merkletree module as a temporary function to ease us transition to the new claims specification.
=> Move generic hash out of merkletree module

core/claim.go, core/claim_test.go, go.mod, go.sum, merkletree/merkletree.go
Merkle tree entries were modified from variable length byte arrays to using 4
Elements.  This commit updates the claims to make them smaller to fit into 4
Elements.
Resolve #40
=> Implement new spec for claims

cmd/relay/endpoint/id.go, cmd/relay/endpoint/serve.go, services/claimsrv/service.go, services/identitysrv/service.go, services/identitysrv/service_test.go
adding create genesis identity merkle
Add CreateIdGenesis & CalculateIdGenesis, Add endpoint handler for CreateIdGenesis
Add proof of kOp when creating identity genesis merkletree
=> Add Genesis Identity MerkleTree, alternative to Counterfactual Id

core/claim.go, core/claim_test.go, services/signedpacketsrv/service.go
Add ClaimAuthorizeService, that is a claim to authorize a Service for the identity that performs the claim.
```
e_3: [ 64  bits] claim type
[ 32  bits] version
[ 157 bits] 0
e_2: [ 248 bits] Hash_k(addr)
[ 5   bits] 0
e_1: [ 248 bits] Hash_k(pubK)
[ 5   bits] 0
e_0: [ 248 bits] Hash_k(domain)
[ 5   bits] 0
```
Where `hash` is the Keccak(input_string)[-248/8:]
```
[0 | Hash_k(domain)][0 | Hash_k(pubK)][0 | Hash_k(addr)][0 | ver | type]
e0                    e1              e2                  e3
```
This claim is used to authorize services to act for the identity that performs the claim, for example, with this claim type, an identity can authorize a Relay, a NotificationsServer, etc to act as their authorized services.
Also, when the identity is discovered through the discovery-protocol, …
=> Add ClaimAuthorizeService

core/claim.go, core/claim_test.go
New Claim type for the specification of the identity.
```go
type ClaimEthId struct {
// Version is the claim version
Version uint32
// Addr is the EthId that will use this identity in the ethereum blockchain
Address	common.Address
// IdentityFactory specifies that the ClaimEthId.Address is an smartcontract, and how this identity is created. It can be just an identitied of the method, or an smartcontract that creates the identity.
// IDEN3 specifies the contract 0x9827348723984729834234 as the factory for its contrafactual identities
// If 0x000.0000, means that is not using an identity creator, and the identity is always available.
IdentityFactory common.Address
}
```
```
e_3: [ 64  bits] claim type
[ 32  bits] version
[ 157 bits] 0
e_2: [ 160 bits] eth address
[ 93   bits] 0
e_1: [ 160 …
```
=> add ClaimEthId

core/id.go, core/id_test.go, core/proof.go, core/proof_test.go, merkletree/merkletree.go
Predicate generation & verification.
Ensures that the MerkleTree is updated incrementally by:
checking that:
- 0: tree is updated incrementally
- claim position was empty in oldRoot
- 1: claim is added correctly
- claim position contains the claim in currentRoot
- 2: claim is not revocated
- claim (version+1) is empty in currentRoot
in case that the claim version != 0:
- 3: claim is at the expected version
- claim (version-1) exist in oldRoot
- 4: current version is incremental from the last one
- siblings of check_0 are inside of check_1
=> add ϕ_min id spec (predicate of ITF)

merkletree/merkletree.go, services/identityagentsrv/service.go, services/identityagentsrv/service_test.go
closes #156 , closes #158 
when issues #167 and #169 are done, will be able to update this with the part of the proof from the Relay (RootUpdater)
=> identityagent: add GetClaimByHi & GetFullMT for one identity

merkletree/merkletree.go
@ed255 removed the merkletree prefix so the tree uses whatever prefix the store already has as specified issue #208.  Let me know if theres anything else.
=> resolves issue #208 by removing the merkletree prefix from NewMerkleTree

core/id.go, core/id_test.go, services/identityagentsrv/service_test.go, services/identitysrv/service_test.go
Update ID type:
```go
// TypeBJP0 specifies the BJ-P0
// - first 2 bytes: `00000000 00000001`
// - curve of k_op: babyjubjub
// - hash function: `Poseidon` v0
TypeBJP0 = [2]byte{0x00, 0x01}
```
& tests updated
=> update id type to TypeBJP0 (BabyJubJub+Poseidon_v0)

core/claims/claim.go, crypto/ecdsa_public_key.go, crypto/signatures.go, merkletree/merkletree.go, merkletree/utils.go
I was having troubles marshaling values into a database and found out that marshalers are more commonly defined on the type and not on the reference to the type, so I changed all the marshalers so that they play nicely with other libraries.
=> Don't use pointers for Marshalers

keystore/keystore.go
keystore Sign & Verify was using internally `Mimc7` instead of `Poseidon`.
Found this while implementing the BabyJubJub signature verification in the smart contracts. This was generating wrong outputs in other packages of go-iden3-core and servers
resolves #328
=> Fix keystore Sign & Verify from Mimc7 to Poseidon

identity/holder/holder.go, identity/issuer/issuer.go, identity/issuer/issuer_test.go
This allows a holder to be created with a genesis only issuer, which means that on Load it won't check the smart contract for it's onchain state.
Resolve #327
=> Allow creating genesis only identities

components/idenpuboffchain/idenpuboffchain.go, components/idenpuboffchain/local/local.go, components/idenpuboffchain/writerhttp/writerhttp.go, components/idenpuboffchain/writerhttp/writerhttp_test.go, components/idenpuboffchain/writermock/writermock.go, components/idenpubonchain/idenpubonchain.go, components/idenpubonchain/local/local.go, components/verifier/verifier_test.go, identity/issuer/issuer.go, identity/issuer/issuer_test.go
This is an implementation of the identity states smart contract in go.  Right now it behaves the same way as the smart contract (that is, it doesn't check any signature).
The idea is to use this in the tests, and to extend it to
- verify the signature
- verify the proof of kOp
Hopefully having this implementation will make testing the real smart contract easier!
=> Add a local implementation of idenpubonchain and idenpuboffchain

components/verifier/verifier.go, components/verifier/verifier_test.go, core/claims/claimAuthorizeKSignBabyJub_test.go, core/claims/claimBasic_test.go, core/claims/revocationrootsleafs_test.go, identity/holder/holder.go, identity/issuer/issuer.go, merkletree/merkletree.go, merkletree/merkletree_test.go, merkletree/node.go, merkletree/utils.go, merkletree/utils_test.go
Adds the error managing to the Poseidon Hash calls, instead of giving a panic when the error is reached. Updates the rest of packages on the new usage of the functions where the hash is involved.
The error when calling Poseidon Hash should never be reached, as is only triggered when the inputs of the hash are outside the Finite Field. But, as this is a core package used by other packages, the panic should not exist or at least should not be reachable.
We evaluated also an 'approach B' ( https://github.com/iden3/go-iden3-core/tree/fix/348b ), where the panic still is there but should never be reachable, as the solution is around creating a secure API wrapping ElemBytes in a way that is impossible to create new ones outside the Finite Field (returning an error in the case that is outside), …
=> Fix #348 approach A

identity/issuer/issuer.go, identity/issuer/issuer_test.go
Resolve #379 
Previously if the Issuer.PublishState got an error when calling the smart contract, the Issuer got into a corrupted state that didn't let it advance further.  Now the PublishState is divided into two atomic parts:
1- Calculate new State
2- Generate zkproof and call smart contract
If the 1st part succeeds but the 2nd doesn't, the next call to PublishState only goes through 2nd part allowing the smart contract call error to be corrected.
Note: This bug was detected when the testing address didn't have enough funds.
=> Fix Issuer.PublishState consistency

claim.go, claim_test.go
- swap endianness for schema on claim creation
- get schema hash returns unswapped bytes
=> swap endianness for schema

.github/workflows/lint.yaml, claim.go
The identifiers of the type `SchemaHash` have different declarations in the file [claim.go.](https://github.com/iden3/go-iden3-core/blob/master/claim.go)
The following declarations exist as of now:
- schemaHash: [\[1\]](https://github.com/iden3/go-iden3-core/blob/07a627943f17945929488f45b777ddbc89a649ca/claim.go#L102) [\[2\]](https://github.com/iden3/go-iden3-core/blob/07a627943f17945929488f45b777ddbc89a649ca/claim.go#L282) [\[3\]](https://github.com/iden3/go-iden3-core/blob/07a627943f17945929488f45b777ddbc89a649ca/claim.go#L282)
- schema: [\[1\]](https://github.com/iden3/go-iden3-core/blob/07a627943f17945929488f45b777ddbc89a649ca/claim.go#L319)
- sc: [\[1\]](https://github.com/iden3/go-iden3-core/blob/07a627943f17945929488f45b777ddbc89a649ca/claim.go#L94) …
=> make identifier declaration of type `SchemaHash` consistent

README.md
The README states this is a GPL-3 repository but the GitHub repository and LICENSE file states this is AGPL-3.0.
This PR corrects the README to what I believe is the intended license. It might be best to just direct to LICENSE entirely.
=> Update README with AGPL license

chain.go
Fix chainId for polygon zkEVM cardona that is now with 1442 like the old zkEVM testnet and should be 2442.
=> fix chainid for polygon zkevm cardona
